; PlatformIO Project Configuration File for TraceFresh Smart Monitoring Node (TF-NODE-01 / TF-NODE-02)
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev
src_dir = src
include_dir = include

[env:esp32dev]
platform = espressif32 @ ^6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    mikalhart/TinyGPSPlus @ ^1.0.3

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=8192
